import './globals.css';

import type { Metadata } from 'next';

import Footer from './(components)/_page-components/footer';
import Header from './(components)/_page-components/header';
import { auth } from '../../auth';
import { ProviderSession } from './session';

const poppins = {
  variable: "--font-poppins",
  subsets: ["latin"],
};

export const metadata: Metadata = {
  title: "Pawa Vote",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <ProviderSession session={session}>

        <body className={`${poppins.variable} antialiased`}>
          <Header />
          <div className="min-h-screen">

            {children}
          </div>
          <Footer />
        </body>
      </ProviderSession>
    </html>
  );
}

