import './globals.css';

import type { Metadata } from 'next';

import Footer from './(components)/_page-components/footer';
import Header from './(components)/_page-components/header';

const poppins = {
  variable: "--font-poppins",
  subsets: ["latin"],
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Header/>
        <div className="min-h-screen">

        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}

